# Generated by Django 5.1.2 on 2024-12-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_desc', models.TextField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(default='No content available')),
                ('news_image', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
