# Generated by Django 5.1.2 on 2024-12-10 15:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
